default_platform(:ios)

platform :ios do
  lane :build do
    api_key = app_store_connect_api_key()
    sync_code_signing(api_key: api_key, type: "appstore")
    build_app(
	workspace: "Runner.xcworkspace",
	scheme: "Runner",
	export_options: {
		method: "app-store",
	}
    )
  end
  lane :upload do
    api_key = app_store_connect_api_key()
    deliver(
	api_key: api_key,
	skip_screenshots: true,
	skip_metadata: true,
	skip_app_version_update: true,
	force: true,
    )
  end
end
