default_platform(:ios)

platform :ios do
  lane :build do
    app_store_connect_api_key
    sync_code_signing(type: "appstore")
    build_app(
	workspace: "Runner.xcworkspace",
	scheme: "Runner",
	export_options: {
		method: "app-store",
	}
    )
  end
  lane :upload do
    app_store_connect_api_key
    deliver
  end
end
